### PR TITLE
Making sure you cant change your username in use by another user

### PR DESCRIPTION
**Pull request by rickardliljeberg**
It compares the object sent in with the object in database, which works in EF assuming the object you send in is attached.

however I have never used Raven or Mongo and can't vouch that it's the same there.

### CODE REVIEW

**Comment by OdeToCode** [comment]
Thanks @rickardliljeberg ! Will check this out first thing tomorrow.

**Comment by OdeToCode** [comment]
Looks like the RavenDb provider needs fixed up before I can build.  I think that is probably simple, but I might not have time this week.

**Comment by rickardliljeberg** [comment]
No worries, I will test the user grouping feature more then maybe we can look at all at once.

**Comment by OdeToCode** [comment]
Thanks!

**Pull request merged**
